logger:
  default: warning
  logs:
    homeassistant.components.rest: critical
    homeassistant.components.sensor: error

homeassistant:
  packages:
    ugreen_nas:
      # rest:            !include conf/ugreen_nas_rest.yaml
      input_text:        !include conf/ugreen_nas_input_text.yaml
